### ISSUE TITLE
Share iree_tests workflow steps more directly with other repos

### ISSUE THREAD

**Issue by ScottTodd** [nod-ai/SHARK-TestSuite#288]
We're duplicating some workflow code between these files:

* https://github.com/nod-ai/SHARK-TestSuite/blob/main/.github/workflows/test_iree.yml 
* https://github.com/iree-org/iree/blob/main/.github/workflows/pkgci_regression_test.yml

Most of the duplication is boilerplate and keeping it synced across commits is a bit of a chore. See https://docs.github.com/en/actions/using-workflows/avoiding-duplication for the options available to us.

I'm imagining something downstream like

```yml
jobs:
  test_onnx:
    steps:
      - name: Check out external TestSuite repository
        uses: actions/checkout@v4.1.7
        with:
          repository: nod-ai/SHARK-TestSuite
          ref: v1
          path: SHARK-TestSuite
          submodules: false
          lfs: false
      - name: Run onnx tests
         uses: SHARK-TestSuite/.github/workflows/test_onnx.yml
         with:
           pytest_flags: ...
           config_file: ...
```

or 
```yml
test_onnx:
  uses: iree-org/test-suite@v1  # or nod-ai/iree-test-suite
  with:
    pytest_flags: ...
    config_file: ...    
```

where the workflow would include running tests, checking for diffs in the config file and uploading the new file(s), etc.
